### ISSUE TITLE
Provide an implementation of a spellchecker that uses NHunspell

### ISSUE THREAD

**Issue by SeanFarrow** [aarondandy/we-cant-spell#3]
It would be nice to have a full implementation of a spell checker that uses NHunspell rather than just a debug spell checker.
I would do this myself, but I can't see how to load the dictionaries you provide in .net standard.

**Comment by aarondandy** [comment]
I wrote a port myself to do just that. I have been real busy with work the last two weeks so have not had a chance to wire it all up yet. I was first going to focus on making sure I have the roslyn analyzer working how I wanted and then wire a proper spell checker up to it. My other project where I ported the Hunspell project to .NET standard can be found here: https://github.com/aarondandy/WeCantSpell.Hunspell

**Comment by SeanFarrow** [comment]
Any idea how long this might take, I’ve got a commercial customer wanting this?
I’m happy to wait if it’s not going to be a long process?

**Comment by aarondandy** [comment]
I don't have any dates in place yet with respect to completing this but I do hope to get some milestones added. You can watch the project to see it's progress. I have not had any time to solidify any of the design and write it down yet but if you are willing to help I would be more than happy to discuss it over discord or hangouts or something, let me know.

**Comment by SeanFarrow** [comment]
Happy to help where I can, is Skype any good, I’m visually impaired?
Kind regards
Sean.

**Comment by aarondandy** [comment]
Sure, I'm aaron.dandy@live.com and should be around. I'll pop the client open here and there.

**Comment by aarondandy** [comment]
I recommend checking out https://github.com/BrightLight/YouShouldSpellcheck.Analyzer
